# Generated by Django 5.2.5 on 2026-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Business', 'Business'), ('Education', 'Education'), ('Finance', 'Finance'), ('Government', 'Government'), ('Health', 'Health'), ('Hospitality', 'Hospitality'), ('Human Services', 'Human Services'), ('IT', 'IT'), ('Law', 'Law'), ('Manufacturing', 'Manufacturing'), ('Sales', 'Sales'), ('Science', 'Science'), ('Transport', 'Transport')], help_text='The generic field predicted by the AI (e.g., IT, Business).', max_length=50)),
                ('official_name', models.CharField(help_text='The exact official course name offered by your university.', max_length=200)),
            ],
            options={
                'verbose_name': 'University Major Mapping',
                'verbose_name_plural': 'University Major Mappings',
                'ordering': ['ml_category', 'official_name'],
            },
        ),
    ]
