# Generated by Django 5.2.5 on 2026-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Business', 'Business'), ('Education', 'Education'), ('Finance', 'Finance'), ('Government', 'Government'), ('Health', 'Health'), ('Hospitality', 'Hospitality'), ('Human Services', 'Human Services'), ('IT', 'IT'), ('Law', 'Law'), ('Manufacturing', 'Manufacturing'), ('Sales', 'Sales'), ('Science', 'Science'), ('Transport', 'Transport')], help_text='The generic field predicted by the AI.', max_length=50)),
                ('job_title', models.CharField(help_text='A potential job or career path (e.g., Software Engineer).', max_length=200)),
            ],
            options={
                'verbose_name': 'Career Path Mapping',
                'verbose_name_plural': 'Career Path Mappings',
                'ordering': ['ml_category', 'job_title'],
            },
        ),
    ]
