# Generated by Django 5.2.5 on 2026-03-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_careerpath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerpath',
            options={'ordering': ['university_major', 'job_title'], 'verbose_name': 'Career Path Mapping', 'verbose_name_plural': 'Career Path Mappings'},
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='ml_category',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='university_major',
            field=models.ForeignKey(default=1, help_text='The specific university program this career belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='ml_engine.universitymajor'),
            preserve_default=False,
        ),
    ]
